apiVersion: v1
kind: Service
metadata:
  name: image-gen
  namespace: default
  labels:
    app: image-gen
spec:
  type: ClusterIP
  ports:
  - port: 9090
  selector:
    app: image-gen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-gen
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-gen
  template:
    metadata:
      labels:
        app: image-gen
    spec:
      containers:
        - name: image-gen
          image: gcr.io/rock-solid-robots/image-gen:latest
          ports:
            - containerPort: 9090